name: Debug Fetch Players Detail

on:
  workflow_dispatch: # nur manuell starten

jobs:
  debug-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Debug Fetch Players Detail
        run: node scripts/fetch_players_detail.js

      - name: Upload Debug Output
        uses: actions/upload-artifact@v4
        with:
          name: debug-players-output
          path: data/debug-players.json
